# Note on the LLMs

We are aware of the 800-pound _Gorilla gorilla gorilla_ in the room: we live in times where any basic programming task can be effectively (if not efficiently or exactly correctly) completed by a large language model. We refrain from the moral judgment on LLMs in our classes; it is a fact of life that students use LLM whether we like it or not, whether it is useful or not, or whether it is ethical to do so (see the [analysis of recent survey of ChatGPT users](https://arstechnica.com/ai/2025/09/seven-things-we-learned-from-openais-first-study-on-chatgpt-usage/)).

However, in order to use LLMs effectively, students must understand what they are doing, which is not the case for the majority in the first few weeks of learning coding. Without understanding of why and how things work, students are unable to judge the LLM's output; even when they copy-paste the code and it works, they will not be able to solve a similar or related task next time.

This phenomenon - that LLMs are useful only when you already have a good idea what you need to do - is discussed well by prof. Ethan Mollick in his post [15 Times to use AI, and 5 Not to](https://www.oneusefulthing.org/p/15-times-to-use-ai-and-5-not-to). His final paragraph (emphasis mine):

> Knowing when to use AI turns out to be a form of wisdom, not just technical knowledge. _Like most wisdom, it's somewhat paradoxical: AI is often most useful where we're already expert enough to spot its mistakes, yet least helpful in the deep work that made us experts in the first place. It works best for tasks we could do ourselves but shouldn't waste time on, yet can actively harm our learning when we use it to skip necessary struggles._ 

Here is another great quote on the issue of effortful development of expertise that is missing when the solutions are easily and immediately available by Andy Heiss, from his essay [AI for Me, Not (Yet) for Thee? Desirable Difficulties and Deliberate Friction with LLMs](https://stats.andrewheiss.com/pinky-lychee/):

> If learners can generate working code through a Google search, if they can upload a blank problem set template and get a completed assignment in seconds, and if they can design, carry out, and analyze research projects in minutes, how can they build the expertise that is required to work with LLM output? Relatedly, if experienced researchers spend the bulk of their time reviewing LLM output and not working through code themselves, what happens to their expertise? The answer to these questions, I argue, is to deliberately introduce difficulty and friction in quantitative work, allowing learners to build expertise and helping experienced researchers maintain it.

This essay becomes a **required reading** for students on Research Skills 2 from 26/27 academic year. Similarly, an essay by Patrick Lin is worth reading, as it provides student-centred discussion of pros and cons of using AI in general, not necessarily related to coding: [Why We’re Not Using AI in This Course, Despite Its Obvious Benefits](https://emergingethics.substack.com/p/why-were-not-using-ai-in-this-course?triedRedirect=true).

We do not directly _teach_ the use of LLMs for coding, as we consider the purpose of the classes to be to acquire fundamental competencies in programmatic data analysis, which students must be able to do without code producers like LLMs. But the LLMs can be good _tutors_ for students learning to code on their own, and with that view in mind, we highly recommend the [AI TutoR textbook](https://psyteachr.github.io/AITutoR/), which guides learners to be more proficient users of LLMs, particularly in coding-related tasks.

Last but not least, we should all be remember that LLMs are maily an extremely sophisticated autocomplete algorithms and be aware of [the Eliza Effect](https://sites.google.com/view/elizaarchaeology/blog/3-weizenbaums-secretary): 

> The Eliza Effect is the propensity for humans to ascribe understanding and intelligence to computer systems. Hofstadter (1995: 167) described it as “the susceptibility of people to read far more understanding than is warranted into strings of symbols - especially words - strung together by computers”, a compelling description written in 1995 but which accurately describes generative AI systems today like ChatGPT. Similarly, Turkle described that “the Eliza effect refers to our more general tendency to treat responsive computer programs as more intelligent than they really are. Very small amounts of interactivity cause us to project our own complexity onto the undeserving object” (Turkle 1997: 101).
