# Practice Questions

::: callout-note
This exercise sheet is all about getting comfortable with RStudio and the tidyverse. In it you will find exercises ranging from individual use of functions to practicing exercises that will allow you to better manipulate data sets.
:::
```{r}
library(webexercises)

```

## Mastering the Basics

1.  
```{r}
opts <- c("install.package", 
            "install.packages", 
            answer = "library", 
            "libraries")
q1 <- mcq(opts)

cat("What function loads a package that is already on your computer?", q1) 
```

2.
```{r}
cat("What library do you need to load in your data set?", q2)
opts2 <- c("tidyverse", 
            "rodents_full", 
            answer = "here", 
            "select from computer")
q2 <- mcq(opts2)

```


3.  
```{r}
cat("Which function should I use to load in a comma separated dataset?", q3)
opts3 <- c("read_csv", 
            "read_tsv", 
            answer = "he", 
            "read_xsxl")
q3<- mcq(opts3)
```

4.  
```{r}
cat("What function is used to select specific columns from a dataset?", q4)
opts4 <- c("filter", 
            answer = "select", 
            "column", 
            "group_by")
q4 <- mcq(opts4)
```

5.  
```{r}
cat("What function is used to select specific rows from a dataset?", q5)
opts5 <- c(answer = "filter", 
            "arrange", 
            "summarise", 
            "select")
q5 <- mcq(opts5)
```

6.  
```{r}
cat("Which function is used to add new columns or modify existing ones?", q6)
opts6 <- c("summarise", 
            "tibble", 
            "summary", 
					 answer = "mutate")
q6 <- mcq(opts6)
```

7.  
```{r}
cat("Which line of code is correctly formatted?", q2)
opts2 <- c("tidyverse", 
            "rodents_full", 
            answer = "filter == ", 
            "select from computer")
q2 <- mcq(opts2)
```

8.  
```{r}
cat("What library do you need to load in your data set?", q2)
opts2 <- c("tidyverse", 
            "rodents_full", 
            answer = "here", 
            "select from computer")
q2 <- mcq(opts2)
```

9.  
```{r}
cat("What library do you need to load in your data set?", q2)
opts2 <- c("tidyverse", 
            "rodents_full", 
            answer = "here", 
            "select from computer")
q2 <- mcq(opts2)
```

10. 
```{r}
cat("What library do you need to load in your data set?", q2)
opts2 <- c("tidyverse", 
            "rodents_full", 
            answer = "here", 
            "select from computer")
q2 <- mcq(opts2)
```

## Working with ggplot

1.  

2.  

3.  

4.  

5.  

6.  

7.  

8.  

9.  

10. 

## Manipulating data sets

1.  

2.  

3.  

4.  

5.  

6.  

7.  
