# Installing R and R Studio on your computer

-   This step-by-step guide will show you how to install R and R Studio
    on your computer.

## Why do I need to install this on my computer?

-   To fully understand and be capable of using R, you will need to
    practice extensively beyond what is shown in class, hence why it is
    highly recommended to install R on your personal devices.

# Installation Issues:

If you're unable to install any software on your computer or your only
device is a tablet/ Chromebook, ignore the following instructions and
switch to the next section **"Using R and R Studio in a web browser"**.

# Important Notes:

**OneDrive users:**

-   DO NOT install the RTools, R or R Studio programs below in your
    OneDrive cloud folder.
-   These applications must be on your actual hard drive (also known as
    C drive).
-   However, you can place your project folders and files on your
    OneDrive.

**Computers in JPSG/17 and JPSG/26:**

-   All packages required to run R (RTools, R and R Studio) are
    installed on every computer in JPSG/17 and JPSG/26. If you are using
    any of those computers, skip to the **"Setting up R and R Studio"**
    section to complete the set-up.

# Download RTools or Command Line Tools:

-   You need to make sure your computer is ready for the installation of
    R and R Studio.

-   You can do that with the help of RTools.

-   We recommend installing RTools (on Windows devices) or Command Line
    Tools (on Mac) as it allows for the installation of various external
    packages (which we will be frequently using).

## RTools for Windows

Instructions and installation are on this page:
**https://cran.r-project.org/bin/windows/Rtools/**. Remember to download
the latest version of RTools (4.4).

## Command Line Tools for macOS

To install the latest version:

1.  Open Terminal app on your mac

2.  Copy and paste (or type) the following command

`xcode-select --install`

then press "Enter":

3.  Follow the instructions. Note that the download may take a while as
    it is a large file.

# Download and install R

## Windows devices

-   Use this link to download and install R:
    **https://www.stats.bris.ac.uk/R/bin/windows/base/**

## macOS devices:

-   Use this link to download and install R:
    **https://www.stats.bris.ac.uk/R/bin/macosx/base/**

# Download and install R Studio

## Windows and macOS devices:

-   Use this link: **https://posit.co/download/rstudio-desktop/**.Click
    on the button "Install R Studio". You are able to use the same link
    for both devices, as your operating system will be instantly
    recognized.

# Next

-   Once you have successfully installed RTools, R and R Studio on your
    computer, go to the next section called **"Setting up R and R
    Studio"**.