# Tidyverse vs base R

When you are going to search for information about some functions, packages or simply ways of doing something in R, you may encounter mentions of `base R` or `tidyverse`. Both are variants of R syntax, the way of writing code to achieve the same goal. `base R` is the "original" R syntax, and all its functions are included by default in R. [`tidyverse`](https://www.tidyverse.org) dialect, served through a series of packages, was developed more recently and needs to be installed and loaded first before it can be used. Both dialects can work together and often it is a matter of personal preference which one to use in a given situation.

This book, and our other teaching resources, are almost entirely written with the [`tidyverse`](https://www.tidyverse.org) dialect of R in mind, using [RStudio](https://posit.co/products/open-source/rstudio/?sid=1) as an integrated development environment (IDE). Base R is only mentioned when we get to square brackets' indexing of lists in the advanced chapters on functions and loops (which we do not teach until the final year). Many of the plotting options described in the [R Graphics Cookbook](https://r-graphics.org) textbook also use base R (in addition to ggplot). 

The reason for our preference for tidyverse is that we consider `tidyverse` to be easier for beginners to grasp. 99% of what we need to do in the year is available through `tidyverse`. `tidyverse` packages have better help sources available online and they are consistent: operating on data frames with a relatively small number of usefully-named functions makes it easier to climb the learning curve. From a beginner student point of view, it might be useful to specify which dialect to use when searching for help online, or by [asking an LLM for support](llms.html).

::: callout-tip
## Recommended reading
We highly recommend reading the following sources to understand the base R vs. `tidyverse` story:

- For the historical overview, read ([or watch](https://www.youtube.com/watch?v=5033jBHFiHE)) Roger Penn's [Teaching R to New Users - From tapply to the Tidyverse](https://simplystatistics.org/posts/2018-07-12-use-r-keynote-2018/).
- David Robinson's [Teach the tidyverse to beginners](http://varianceexplained.org/r/teach-tidyverse/) post that first inspired Jarek to switch to `tidyverse` after a year of teaching base R + `ggplot`.
- Not everyone agrees that `tidyverse` is better, or is better for teaching R, and the two recent contrarian views come from Norm Matloff ([Teaching R in a Kinder, Gentler, More Effective Manner](https://matloff.github.io/TidyverseSkeptic/Skeptic.html)) and Robert München ([Why R is Hard to Learn](https://r4stats.com/articles/why-r-is-hard-to-learn/)).
:::